# Generated by Django 4.1.3 on 2022-12-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
